participant :TasksPresenter as tp
participant :TasksLoader as tl
participant LoadManager as lm

tp->*tl: create
tp->lm: initLoader(1, null, this)
lm->tp: onCreateLoader(1, null)
tp-->lm: :TaskLoader
lm->+tl: onStartLoading()

alt previously loaded data available
tl->tl: deliverResult(:List<Task>)
else
tl->tl: forceLoad()
tl->tl: loadInBackground()\nreturns :List<Task>
tl->tl: deliverResult(:List<Task>)
end

tl-->-lm:
lm->tp: onLoadFinished(:TasksLoader, :List<Task>)
